print(
    "\nLongitudes\n"
    "========================\n"
    "OPCIONES: \n"
    "1. Mt a Km\n"
    "2. Mt a Pie\n"
    "3. Mt a Mi\n"
    "4. Km a M\n"
    "5. Km a Pie\n"
    "6. Km a Mi\n"
    "7. Pie a M\n"
    "8. Pie a Km\n"
    "9. Pie a Mi\n"
    "10. Mi a M\n"
    "11. Mi a Km\n"
    "12. Mi a Pie\n"
    "0. Retroceder\n"
)
